name: deceasefinder
description: decease finder application by yasiru

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_ticket: ^1.0.1
  camera: ^0.8.1
  http: ^0.13.3
  dio: ^5.0.0
  webview_flutter: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section,
  assets:
    - assets/
